import type {
  Booking,
  CashMovement,
  Guest,
  Invoice,
  Payment,
  Room,
} from "@/lib/types"

export const property = {
  name: "Riad Al Fes",
  legalName: "Riad Al Fes SARL",
  city: "Fes",
  country: "Morocco",
  phone: "+212 600 000 000",
  ice: "001234567000089",
  defaultCurrency: "MAD",
  touristTax: "30 MAD per person per night",
  vatRate: "10%",
}

export const rooms: Room[] = [
  {
    id: "zellij-suite",
    name: "Zellij Suite",
    capacity: 2,
    rates: { MAD: 900, EUR: 85, USD: 95 },
    active: true,
  },
  {
    id: "andalusia-room",
    name: "Andalusia Room",
    capacity: 2,
    rates: { MAD: 750, EUR: 70, USD: 80 },
    active: true,
  },
  {
    id: "medina-room",
    name: "Medina Room",
    capacity: 3,
    rates: { MAD: 1000, EUR: 95, USD: 105 },
    active: true,
  },
  {
    id: "terrace-room",
    name: "Terrace Room",
    capacity: 2,
    rates: { MAD: 800, EUR: 75, USD: 85 },
    active: true,
  },
  {
    id: "family-suite",
    name: "Family Suite",
    capacity: 4,
    rates: { MAD: 1300, EUR: 120, USD: 135 },
    active: true,
  },
]

export const initialBookings: Booking[] = [
  {
    id: "booking-1",
    guestName: "John Miller",
    roomId: "zellij-suite",
    checkIn: "2026-06-01",
    checkOut: "2026-06-04",
    guests: 2,
    source: "Booking.com",
    amount: 270,
    currency: "EUR",
    status: "confirmed",
    notes: "Airport pickup requested.",
  },
  {
    id: "booking-2",
    guestName: "Sarah Johnson",
    roomId: "family-suite",
    checkIn: "2026-06-03",
    checkOut: "2026-06-06",
    guests: 4,
    source: "Airbnb",
    amount: 390,
    currency: "USD",
    status: "confirmed",
    notes: "Family breakfast at 9:00.",
  },
  {
    id: "booking-3",
    guestName: "Ahmed Benali",
    roomId: "medina-room",
    checkIn: "2026-06-05",
    checkOut: "2026-06-07",
    guests: 3,
    source: "Direct",
    amount: 2000,
    currency: "MAD",
    status: "confirmed",
    notes: "Paying cash on arrival.",
  },
  {
    id: "booking-4",
    guestName: "Emily Carter",
    roomId: "terrace-room",
    checkIn: "2026-06-07",
    checkOut: "2026-06-10",
    guests: 2,
    source: "Walk-in",
    amount: 2400,
    currency: "MAD",
    status: "confirmed",
    notes: "Needs printed invoice draft.",
  },
  {
    id: "booking-5",
    guestName: "Laura Smith",
    roomId: "andalusia-room",
    checkIn: "2026-06-09",
    checkOut: "2026-06-12",
    guests: 2,
    source: "HotelRunner",
    amount: 240,
    currency: "USD",
    status: "confirmed",
    notes: "Late check-in after 22:00.",
  },
]

export const guests: Guest[] = [
  {
    id: "guest-1",
    fullName: "John Miller",
    phone: "+1 415 555 0101",
    email: "john.miller@example.com",
    nationality: "United States",
    documentNumber: "P1234567",
    notes: "Returning guest.",
  },
  {
    id: "guest-2",
    fullName: "Sarah Johnson",
    phone: "+1 212 555 0198",
    email: "sarah.johnson@example.com",
    nationality: "United States",
    documentNumber: "P7742901",
    notes: "Travelling with two children.",
  },
  {
    id: "guest-3",
    fullName: "Ahmed Benali",
    phone: "+212 661 111 222",
    email: "ahmed.benali@example.com",
    nationality: "Morocco",
    documentNumber: "CN445566",
    notes: "Prefers WhatsApp.",
  },
  {
    id: "guest-4",
    fullName: "Emily Carter",
    phone: "+44 7700 900123",
    email: "emily.carter@example.com",
    nationality: "United Kingdom",
    documentNumber: "P9988776",
    notes: "Vegetarian breakfast.",
  },
  {
    id: "guest-5",
    fullName: "Laura Smith",
    phone: "+1 646 555 0147",
    email: "laura.smith@example.com",
    nationality: "United States",
    documentNumber: "P4422119",
    notes: "Asks for terrace view.",
  },
]

export const payments: Payment[] = [
  {
    id: "payment-1",
    bookingId: "booking-1",
    guestName: "John Miller",
    amount: 135,
    currency: "EUR",
    method: "OTA prepaid",
    paymentDate: "2026-05-20",
    notes: "Booking.com partial payout.",
  },
  {
    id: "payment-2",
    bookingId: "booking-3",
    guestName: "Ahmed Benali",
    amount: 1000,
    currency: "MAD",
    method: "cash",
    paymentDate: "2026-06-05",
    notes: "Cash deposit at check-in.",
  },
  {
    id: "payment-3",
    bookingId: "booking-4",
    guestName: "Emily Carter",
    amount: 2400,
    currency: "MAD",
    method: "cash",
    paymentDate: "2026-06-07",
    notes: "Paid in full.",
  },
]

export const cashMovements: CashMovement[] = [
  {
    id: "cash-1",
    date: "2026-06-07",
    type: "opening balance",
    category: "daily balance",
    amount: 6200,
    currency: "MAD",
    notes: "Start of day.",
  },
  {
    id: "cash-2",
    date: "2026-06-07",
    type: "cash in",
    category: "room payment",
    amount: 2400,
    currency: "MAD",
    notes: "Emily Carter stay.",
  },
  {
    id: "cash-3",
    date: "2026-06-07",
    type: "cash out",
    category: "food",
    amount: 320,
    currency: "MAD",
    notes: "Breakfast supplies.",
  },
  {
    id: "cash-4",
    date: "2026-06-07",
    type: "closing balance",
    category: "daily balance",
    amount: 8280,
    currency: "MAD",
    notes: "Expected drawer total.",
  },
]

export const invoices: Invoice[] = [
  {
    id: "INV-DRAFT-001",
    bookingId: "booking-4",
    guestName: "Emily Carter",
    status: "draft",
    total: 2400,
    currency: "MAD",
    issueDate: "2026-06-07",
  },
  {
    id: "INV-DRAFT-002",
    bookingId: "booking-3",
    guestName: "Ahmed Benali",
    status: "draft",
    total: 2000,
    currency: "MAD",
    issueDate: "2026-06-05",
  },
]
