ALTER TABLE "IcalFeed" ADD COLUMN "lastImportStatus" TEXT;
ALTER TABLE "IcalFeed" ADD COLUMN "lastImportMessage" TEXT;
ALTER TABLE "IcalFeed" ADD COLUMN "lastImportImported" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "IcalFeed" ADD COLUMN "lastImportUpdated" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "IcalFeed" ADD COLUMN "lastImportSkipped" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "IcalFeed" ADD COLUMN "lastImportErrors" INTEGER NOT NULL DEFAULT 0;
